version: '2'

services:

  jirabot:
    image: 'jira-bot:latest'
    build:
      context: .
    container_name: jirabot
    depends_on:
      - db
    ports:
      - 5005:5005
    env_file:
      - docker/jirabot.env
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - SPRING_PROFILES_ACTIVE=sdk
      - spring.datasource.dialect=org.hibernate.dialect.PostgreSQL14Dialect
    volumes:
      - jirabot_logs:/log

  db:
    image: 'postgres:14-alpine'
    container_name: db
    ports:
      - "5434:5432"
    env_file:
      - docker/jirabot.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
