name: deploy-jira-bot
run-name: ${{ github.actor }} is pushing source code to host to deploy jira-bot there
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into remote host, push source files, and trigger docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JIRABOT_HOST }}
          username: ${{ secrets.JIRABOT_HOST_USER }}
          key: ${{ secrets.JIRABOT_HOST_SSH_KEY }}
          script: |
            # SSH into the remote host with StrictHostKeyChecking disabled
            ssh -o "StrictHostKeyChecking no" ${{ secrets.JIRABOT_HOST_USER }}@${{ secrets.JIRABOT_HOST }}

            # Change directory to the GitHub repository root
            cd $GITHUB_WORKSPACE

            # Copy source files to the remote host
            scp -r ./* ${{ secrets.JIRABOT_HOST_USER }}@${{ secrets.JIRABOT_HOST }}:/home/user1/test

#            # SSH into the remote host and trigger docker-compose
#            ssh ${{ secrets.JIRABOT_HOST_USER }}@${{ secrets.JIRABOT_HOST }} 'cd /opt/jirabot_project/karmabot && docker-compose up --build'



