name: deploy-jira-bot
run-name: ${{ github.actor }} is pushing source code to host to deploy jira-bot there
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event."

  deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Push source files to remote host
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.JIRABOT_HOST }}
#          username: ${{ secrets.JIRABOT_HOST_USER }}
#          key: ${{ secrets.JIRABOT_HOST_SSH_KEY }}
#          port: ${{ secrets.JIRABOT_HOST_PORT }}
#          source: "./*"
#          target: "/home/user1/test"

      - name: Run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JIRABOT_HOST }}
          username: ${{ secrets.JIRABOT_HOST_USER }}
          key: ${{ secrets.JIRABOT_HOST_SSH_KEY }}
          port: ${{ secrets.JIRABOT_HOST_PORT }}
          script: |
            # SSH into the remote host and trigger docker-compose
            ssh ${{ secrets.JIRABOT_HOST_USER }}@${{ secrets.JIRABOT_HOST }} 'cd /opt/jirabot_project/karmabot && docker compose up --build'
